name: kolibri-docker-image-build

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: kolibri

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses kolibri
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          source utils.sh
          alpine_arm_sha=$(get_manifest_sha "treehouses/alpine:latest" "arm")
          echo $alpine_arm_sha
          kolibri_arm_sha=$(get_manifest_sha "neethumohan1212/kolibri:latest" "arm")
          echo $kolibri_arm_sha
          flag_arm=$(is_base "treehouses/alpine@"$alpine_arm_sha "neethumohan1212/kolibri@"$kolibri_arm_sha)
          echo $flag_arm
